### ISSUE TITLE
Build outside of Visual Studio

### ISSUE THREAD

**Issue by awvwgk** [TUHH-TVT/openCOSMO-RS_cpp#1]
Would it be possible to provide a build system, like [meson](https://mesonbuild.com) or [cmake](https://cmake.org), which allows to build openCOSMO-RS outside of Visual Studio?

**Comment by v8git** [comment]
This definitely makes sense. However, at the time we have no capabilities to develop it. I will leave the issue open. If you want, you can also develop it and create a merge request. If you look at how to compile on Linux maybe you might get an idea.

**Comment by ianhbell** [comment]
CMake is essential for C++ projects, agree with @awvwgk

**Comment by v8git** [comment]
I have added the needed file and documentation to build with cmake. Thanks for the idea.
