### ISSUE TITLE
COSMO calculation with ORCA

### ISSUE THREAD

**Issue by kainszs** [TUHH-TVT/openCOSMO-RS_cpp#3]
Good evening,

In your paper you say that you can also perform a COSMO calculation using ORCA. However, their [documentation](https://www.orcasoftware.de/tutorials_orca/prop/CPCM.html#cpcm-and-cosmo) states that there is no COSMO implementation. How did you do that? Which version and which input is necessary? Can the output files also be used for COSMO-RS?

Best regards from Mainz, 
Kai

**Comment by simonmb** [comment]
Hi @kainszs,

You are completely right. ORCA has an implementation of the CPCM model which for all intents and purposes is almost the same model, especially in the limit of epsilon infinity. i.e. the ideal conductor. The conformer generator [here](https://github.com/TUHH-TVT/openCOSMO-RS_conformer_pipeline) allows creating the needed files to use with openCOSMO-RS.
If you were asking to create the needed input files for COSMOtherm, this is unfortunately not supported.
