### ISSUE TITLE
Concentraion for Water Solubility

### ISSUE THREAD

**Issue by kainszs** [TUHH-TVT/openCOSMO-RS_cpp#5]
Hello,
I would like to calculate aqueous solubility. What concentration do I need to enter? And you mentioned in the last issue that you will be releasing a new version soon. Can you tell me approximately when that will be? What features will it offer? Is it worth waiting for it? 

Greetings from Mainz, Kai

**Comment by simonmb** [comment]
Hi @kainszs, please refer to the literature to find how to calculate the solid solubility of a solute in a water. However I can tell you you will need additional information: either the melting temperature and enthalpy, the aqueous formation energy or a reference solubility in a different solvent. Depending on what information is available the reference state of the activity coefficients changes. Whatever method you choose it will be an iterative process as gamma is a function of x. You try different concentrations until the value does not change anymore and converges towards the predicted solubility.

This repository is about the model, not about actual phase equilibrium calculations. Although we have code to do this calculations it is in no state to put it on github as changes would be necessary for making it github ready and more maintainable. If you are interested in contributing please send me an email. There are however other python modules that might be easy to use to calculate phase equilibria using openCOSMO-RS as activity coefficient model.

**Comment by kainszs** [comment]
How can I contact you by email?

**Comment by simonmb** [comment]
I supposed I was easy to find, as there are not many people working on openCOSMO-RS yet. But I sent you a message on LinkedIn
